#!/usr/bin/env python3
"""
build.py — regenerate the minified production bundles.

No framework, no npm — just Python 3 (already on macOS). Run it after you edit
any source CSS/JS, then commit the updated .min files:

    python3 build.py

Inputs  (readable source, safe to edit):
    css/main.css  css/nav.css  css/portfolio.css  css/pages.css
    js/nav.js  js/filter.js  js/modal.js  js/grid.js

Outputs (generated — do not hand-edit):
    css/styles.min.css       <- the 4 CSS files, concatenated + minified
    js/app.min.js            <- nav+filter+modal+grid, concatenated + minified

NOTE: js/projects.js is intentionally NOT minified or bundled. It is your data
file — portfolio.html loads it directly so adding a project is a one-file edit
with nothing to rebuild.
"""

import os, re

ROOT = os.path.dirname(os.path.abspath(__file__))

CSS_FILES = ['css/main.css', 'css/nav.css', 'css/portfolio.css', 'css/pages.css']
JS_FILES  = ['js/nav.js', 'js/filter.js', 'js/modal.js', 'js/grid.js']


def minify_css(src):
    src = re.sub(r'/\*.*?\*/', '', src, flags=re.S)   # strip comments
    src = re.sub(r'\s+', ' ', src)                     # collapse whitespace
    src = re.sub(r'\s*([{}:;,>~])\s*', r'\1', src)     # trim around punctuation
    src = src.replace(';}', '}')                       # drop last semicolon
    return src.strip()


def minify_js(src):
    """Strip comments + indentation safely by scanning char-by-char and
    honouring string / template-literal / regex contexts (so the // in a URL
    like https://… is never mistaken for a comment). Statements stay on their
    own lines to keep automatic-semicolon-insertion safe.

    CAVEAT: does not parse ${...} expressions inside template literals, so a
    NESTED template literal (a backtick inside ${...}) will confuse it. Avoid
    nested template literals in source — precompute with string concatenation
    instead (see js/grid.js locHtml)."""
    out = []
    i, n = 0, len(src)
    # track the previous meaningful char to tell regex `/` from division `/`
    prev = ''
    while i < n:
        c = src[i]
        nxt = src[i + 1] if i + 1 < n else ''

        # line comment
        if c == '/' and nxt == '/':
            i += 2
            while i < n and src[i] != '\n':
                i += 1
            continue
        # block comment
        if c == '/' and nxt == '*':
            i += 2
            while i < n and not (src[i] == '*' and i + 1 < n and src[i + 1] == '/'):
                i += 1
            i += 2
            continue
        # string / template literal — copy verbatim
        if c in ('"', "'", '`'):
            q = c
            out.append(c)
            i += 1
            while i < n:
                out.append(src[i])
                if src[i] == '\\':
                    if i + 1 < n:
                        out.append(src[i + 1])
                        i += 2
                        continue
                elif src[i] == q:
                    i += 1
                    break
                i += 1
            prev = q
            continue
        # regex literal — `/` is a regex if the previous token implies one
        if c == '/' and prev in ('', '(', ',', '=', ':', '[', '!', '&', '|',
                                  '?', '{', '}', ';', '\n', '+', '-', '*', '%',
                                  '<', '>', '~', '^'):
            out.append(c)
            i += 1
            while i < n:
                out.append(src[i])
                if src[i] == '\\':
                    if i + 1 < n:
                        out.append(src[i + 1])
                        i += 2
                        continue
                elif src[i] == '/':
                    i += 1
                    break
                i += 1
            # copy trailing flags
            while i < n and src[i].isalpha():
                out.append(src[i])
                i += 1
            prev = '/'
            continue

        out.append(c)
        if not c.isspace():
            prev = c
        i += 1

    # trim each line, drop blank lines
    lines = [ln.strip() for ln in ''.join(out).split('\n')]
    return '\n'.join(ln for ln in lines if ln)


def read(path):
    with open(os.path.join(ROOT, path), encoding='utf-8') as f:
        return f.read()


def write(path, data):
    with open(os.path.join(ROOT, path), 'w', encoding='utf-8') as f:
        f.write(data)


def main():
    css = '\n'.join(minify_css(read(p)) for p in CSS_FILES)
    write('css/styles.min.css', css + '\n')

    banner = ('/* Generated by build.py from js/nav.js, filter.js, modal.js, '
              'grid.js — do not edit. */\n')
    js = banner + '\n'.join(minify_js(read(p)) for p in JS_FILES)
    write('js/app.min.js', js + '\n')

    def size(p):
        return os.path.getsize(os.path.join(ROOT, p))

    css_src = sum(size(p) for p in CSS_FILES)
    js_src  = sum(size(p) for p in JS_FILES)
    print(f"css/styles.min.css  {size('css/styles.min.css'):>6}b  (from {css_src}b)")
    print(f"js/app.min.js       {size('js/app.min.js'):>6}b  (from {js_src}b)")


if __name__ == '__main__':
    main()
